packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': 9.37.0
  eslint: 9.37.0
  globals: 16.4.0
  prettier: 3.4.2
  typescript: 5.9.3
  typescript-eslint: 8.45.0
  '@types/node': 22.18.8
  zod: 4.1.11
