packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true

catalog:
  '@eslint/js': 9.37.0
  '@types/node': 22.18.8
  '@types/ramda': 0.31.1
  eslint: 9.37.0
  globals: 16.4.0
  prettier: 3.4.2
  typescript: 5.9.3
  typescript-eslint: 8.45.0
  zod: 4.1.11
  ramda: 0.31.3
