packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.8
  '@types/node': 24.10.1
  '@types/ramda': 0.31.1
  ramda: 0.32.0
  typescript: 5.9.3
  zod: 4.1.13

injectWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

syncInjectedDepsAfterScripts:
  - build
