services:
  postgres:
    image: docker.io/postgres:15
    container_name: battleships-postgres
    environment:
      POSTGRES_DB: battleships
      POSTGRES_USER: battleships
      POSTGRES_PASSWORD: super-password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    restart: unless-stopped

volumes:
  postgres_data:
